src/Ibi.TimesheetDiary.Web.Mvc/Controllers/ProjectController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ProjectsController.cs" company="IBI Group">
//   Copyright 2012 IBI Group (UK). Licensed under the Apache License, Version 2.0 (the "License").
// </copyright>
// <summary>
//   Controller for <see cref="Project" /> related actions.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace Ibi.TimesheetDiary.Web.Mvc.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;

    using Ibi.TimesheetDiary.ServiceContracts;

    /// <summary>
    /// Controller for <see cref="Project"/> related actions.
    /// </summary>
    public class ProjectController : ControllerBase
    {
        /// <summary>
        /// Local instance of <see cref="IProjectServices"/>,
        /// </summary>
        private readonly IProjectServices projectServices;

        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectController"/> class.
        /// </summary>
        /// <param name="serviceProviderFactory">The service provider factory.</param>
        public ProjectController(IServiceProviderFactory serviceProviderFactory)
            : base(serviceProviderFactory)
        {
            this.projectServices = serviceProviderFactory.GetProjectServices();
        }

        /// <summary>
        /// Returns a view with a list of all projects.
        /// </summary>
        /// <returns>A view with a list of all projects.</returns>
        public ActionResult Index()
        {
            var projects = this.projectServices.Projects
                .OrderByDescending(x => x.IsChargeable)
                .ThenByDescending(x => x.ProjectCode)
                .ToList();

            return View(projects);
        }

        /// <summary>
        /// Returns a view with details of the specified project.
        /// </summary>
        /// <param name="projectCode">The project code.</param>
        /// <returns>A view with details of the specified project.</returns>
        public ActionResult Details(string projectCode)
        {
            var project = this.projectServices.GetProjectByCode(projectCode);
            return View(project);
        }

        /// <summary>
        /// Returns a view with a form for creating a new <see cref="Project"/>.
        /// </summary>
        /// <returns>A view with a form for creating a new <see cref="Project"/>.</returns>
        public ActionResult Create()
        {
            return View(new Project());
        }

        /// <summary>
        /// Handles the POSTing of a new <see cref="Project"/>.
        /// </summary>
        /// <param name="collection">The collection.</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Project newProject = new Project();
                    if (TryUpdateModel(newProject))
                    {
                        this.projectServices.SaveProject(newProject);
                        return RedirectToAction("Index");
                    }
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e);
            }

            return View();
        }

        /// <summary>
        /// Returns a view with a form for editing a <see cref="Project"/>.
        /// </summary>
        /// <param name="projectCode">The project code of the project to edit.</param>
        /// <returns>A view with a form for editing a project.</returns>
        public ActionResult Edit(string projectCode)
        {
            var project = this.projectServices.GetProjectByCode(projectCode);
            return View(project);
        }

        /// <summary>
        /// Handles the POSTing of an edited <see cref="Project"/>.
        /// </summary>
        /// <param name="projectCode">The project code of the project to edit.</param>
        /// <param name="collection">The from collection.</param>
        /// <returns>A redirect to <see cref="Index"/> if successful; otherwise the
        /// same view with model errors.</returns>
        [HttpPost]
        public ActionResult Edit(string projectCode, FormCollection collection)
        {
            var project = this.projectServices.GetProjectByCode(projectCode);
            try
            {
                if (ModelState.IsValid)
                {
                    if (TryUpdateModel(project))
                    {
                        this.projectServices.SaveProject(project);
                        return RedirectToAction("Index");
                    }

                    return View(project);
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e);
            }

            return View(project);
        }

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Projects/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

src/Ibi.TimesheetDiary.Web.Mvc/Controllers/SubProjectController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="SubProjectController.cs" company="IBI Group">
//   Copyright 2012 IBI Group (UK). Licensed under the Apache License, Version 2.0 (the "License").
// </copyright>
// <summary>
//   Controller for <see cref="SubProject" /> related actions.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace Ibi.TimesheetDiary.Web.Mvc.Controllers
{
    using System;
    using System.Web.Mvc;

    using Ibi.TimesheetDiary.ServiceContracts;

    /// <summary>
    /// Controller for <see cref="SubProject"/> related actions.
    /// </summary>
    public class SubProjectController : ControllerBase
    {
        /// <summary>
        /// Local instance of <see cref="IProjectServices"/>,
        /// </summary>
        private readonly IProjectServices projectServices;

        /// <summary>
        /// Initializes a new instance of the <see cref="SubProjectController"/> class.
        /// </summary>
        /// <param name="serviceProviderFactory">The service provider factory.</param>
        public SubProjectController(IServiceProviderFactory serviceProviderFactory)
            : base(serviceProviderFactory)
        {
            this.projectServices = serviceProviderFactory.GetProjectServices();
        }

        /// <summary>
        /// Returns a view with a list of all sub-projects within the given project.
        /// </summary>
        /// <param name="projectCode">The project code.</param>
        /// <returns>A view with a list of all sub-projects within the given project.</returns>
        public ActionResult Index(string projectCode)
        {
            var project = this.projectServices.GetProjectByCode(projectCode);
            if (project == null)
            {
                return RedirectToAction("Index", "Project");
            }

            ViewBag.ProjectCode = project.ProjectCode;
            return View(project.SubProjects);
        }

        /// <summary>
        /// Returns a view with a form for creating a new <see cref="SubProject"/>.
        /// </summary>
        /// <param name="projectCode">The parent project code.</param>
        /// <returns>A view with a form for creating a new <see cref="SubProject"/>.</returns>
        public ActionResult Create(string projectCode)
        {
            var project = this.projectServices.GetProjectByCode(projectCode);
            if (project == null)
            {
                return RedirectToAction("Index", "Project");
            }

            ViewBag.ProjectCode = projectCode;
            var subProject = new SubProject { Project = project };
            return View(subProject);
        }

        /// <summary>
        /// Handles a POST for creating a new <see cref="SubProject"/>.
        /// </summary>
        /// <param name="projectCode">The parent project code.</param>
        /// <param name="collection">The form collection.</param>
        /// <returns>A redirect to <see cref="Index"/> if successful; otherwise the same
        /// view with errors.</returns>
        [HttpPost]
        public ActionResult Create(string projectCode, FormCollection collection)
        {
            var project = this.projectServices.GetProjectByCode(projectCode);
            if (project == null)
            {
                return RedirectToAction("Index", "Project");
            }

            try
            {
                var newSubProject = new SubProject { Project = project };

                if (TryUpdateModel(newSubProject, null, null, new[] { "Project" }))
                {
                    project.SubProjects.Add(newSubProject);
                    this.projectServices.SaveProject(project);

                    return RedirectToAction("Index", new { projectCode });
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e);
            }

            return View();
        }

        /// <summary>
        /// Returns a view with a form for editing a <see cref="SubProject"/>.
        /// </summary>
        /// <param name="projectCode">The project code of the parent project.</param>
        /// <param name="subNumber">The sub number of the project to edit.</param>
        /// <returns>
        /// A view with a form for editing a sub project.
        /// </returns>
        public ActionResult Edit(string projectCode, int subNumber)
        {
            var project = this.projectServices.GetSubProjectByCodeAndSubNumber(projectCode, subNumber);
            if (project == null)
            {
                return RedirectToAction("Index", new { projectCode });
            }

            return View(project);
        }

        /// <summary>
        /// Handles the POSTing of an edited <see cref="SubProject"/>.
        /// </summary>
        /// <param name="projectCode">The project code of the parent project.</param>
        /// <param name="subNumber">The sub number of the sub project to edit.</param>
        /// <param name="collection">The from collection.</param>
        /// <returns>
        /// A redirect to <see cref="Index"/> if successful; otherwise the
        /// same view with model errors.
        /// </returns>
        [HttpPost]
        public ActionResult Edit(string projectCode, int subNumber, FormCollection collection)
        {
            var project = this.projectServices.GetSubProjectByCodeAndSubNumber(projectCode, subNumber);
            try
            {
                if (ModelState.IsValid)
                {
                    if (TryUpdateModel(project, null, null, new[] { "Project" }))
                    {
                        this.projectServices.SaveSubProject(project);
                        return RedirectToAction("Index", new { projectCode });
                    }

                    return View(project);
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e);
            }

            return View(project);
        }
    }
}

src/Ibi.TimesheetDiary.Web.Mvc/Views/Project/Create.cshtml
@model Ibi.TimesheetDiary.Project

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Project</legend>

        @Html.EditorForModel()

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

src/Ibi.TimesheetDiary.Web.Mvc/Views/Project/Details.cshtml
@model Ibi.TimesheetDiary.Project

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Project</legend>

    <div class="display-label">ProjectCode</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ProjectCode)
    </div>

    <div class="display-label">Name</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">Description</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ProjectId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

src/Ibi.TimesheetDiary.Web.Mvc/Views/Project/Edit.cshtml
@model Ibi.TimesheetDiary.Project

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Project</legend>

        @Html.HiddenFor(model => model.ProjectId)

        @Html.EditorForModel();

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

src/Ibi.TimesheetDiary.Web.Mvc/Views/Project/Index.cshtml
@model IEnumerable<Ibi.TimesheetDiary.Project>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            ProjectCode
        </th>
        <th>
            Name
        </th>
        <th>
            Description
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ProjectCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { projectCode = item.ProjectCode }) |
            @Html.ActionLink("Details", "Details", new { projectCode = item.ProjectCode }) |
            @Html.ActionLink("Delete", "Delete", new { projectCode = item.ProjectCode }) |
            @Html.ActionLink(item.SubProjects.Count + " Sub Projects", "Index", "SubProject", new { projectCode = item.ProjectCode }, null)
        </td>
    </tr>
}

</table>